datos <- c(100, 200, 200, 250, 600)
mean(datos)
median(datos)
as.numeric(names(which.max(table(datos))))
var(datos)
sd(datos)
rango <- max(datos) - min(datos)
range(datos)
sd(datos) / mean(datos)
summary(datos)
min(datos)
quantile(datos, 0.25)
quantile(datos, 0.50)
quantile(datos, 0.75)
max(datos)
quantile(datos, probs = c(0.25, 0.50, 0.75))

table(datos)
prop.table(table(datos))
barplot(datos)
pie(datos)
hist(datos, breaks=100, col = "lightblue")
boxplot(datos)

RI <- quantile(datos, 0.75) -quantile(datos, 0.25)
RI * 1.5